from django.urls import path
from homePage.api.views import *

urlpatterns = [
    path('api_homePage/', api_homePage, name='api_homePage'),
    path('api_register/', api_registration, name='api_register'),
    path('api_login/', api_login, name='api_login'),
    path('api_logout/', api_logoutUser, name='api_logout'),
    path('api_eshop/', api_eShop, name='api_eshop'),
    path('api_cartData/', api_cartData, name='api_cartData'),
    path('api_updateCartData/', api_updateCartData, name='api_updateCartData'),
    path('api_get_PtdDetail_SameCategoryPtd/', api_get_PtdDetail_SameCategoryPtd, name='api_get_PtdDetail_SameCategoryPtd'),
    path('api_getShippingAdd/', api_getShippingAdd, name='api_getShippingAdd'),
    path('api_processOrder/', api_processOrder, name='api_processOrder'),
    path('api_guestVerifyCartItems/', api_guestVerifyCartItems, name='api_guestVerifyCartItems'),
    path('api_adminSession/', api_adminSession, name='api_adminSession'),
    path('api_adminEditOrder/', api_adminEditOrder, name='api_adminEditOrder'),
    path('api_adminProcessRefundOrder/', api_adminProcessRefundOrder, name='api_adminProcessRefundOrder'),
    path('api_myOrderSession/', api_myOrder, name='api_myOrderSession'),
    path('api_updateMyOrder/', api_updateMyOrder, name='api_updateMyOrder'),
    path('api_pendingReview/', api_pendingReview, name='api_pendingReview'),
    path('api_writePtdReview/', api_writePtdReview, name='api_writePtdReview'),
    path('api_wishList/', api_wishList, name='api_wishList'),
    path('api_traderStore/', api_traderStore, name='api_traderStore'),
    path('api_changePassword/', api_changePassword, name='api_changePassword'),
    path('api_productOverView/', api_productOverView, name='api_productOverView'),
    path('api_editProduct/', api_editProduct, name='api_editProduct'),
    path('api_addProduct/', api_addProduct, name='api_addProduct'),
    path('api_settings/', api_settings, name='api_settings'),
    path('api_updateCustomerAddress/', api_updateCustomerAddress, name='api_updateCustomerAddress'),
    path('api_adminSetting/', api_adminSetting, name='api_adminSetting'),
    path('api_ptdCategoryBrand/', api_ptdCategoryBrand, name='api_ptdCategoryBrand'),
    path('api_allRecentView/', api_allRecentView, name='api_allRecentView'),
    path('api_allSellerItems/', api_allSellerItems, name='api_allSellerItems'),
]